Repository makometr/piaa_9383, pull requests merged in 2021-05, with the labels that each got.

#33 Poplavskiy_lab2
  Poplavskiy/lab2/9383_Poplavskiy_lab2.pdf
  Poplavskiy/lab2/Astar.py
  Poplavskiy/lab2/astar_tests.py
  Poplavskiy/lab2/data.txt
  Poplavskiy/lab2/greed.py
  Poplavskiy/lab2/greed_tests.py
Labels: Python, Защита - :fire:, Код - можно поправить, Можно защищать, Режим: 3, Тесты - :1st_place_medal:

#34 Poplavskiy lab3
  Poplavskiy/lab3/9383_Poplavskiy_lab3.pdf
  Poplavskiy/lab3/data_test_1.txt
  Poplavskiy/lab3/data_test_2.txt
  Poplavskiy/lab3/data_test_3.txt
  Poplavskiy/lab3/ford_falk.h
  Poplavskiy/lab3/source.cpp
  Poplavskiy/lab3/tests.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - можно поправить

#23 Likhashva_lab2
  Likhashva/LB2_Lihashva_AD_9383.pdf
  Likhashva/source/AStar/AStar.cpp
  Likhashva/source/AStar/AStar.h
  Likhashva/source/AStar/CMakeLists.txt
  Likhashva/source/GreedyAlg/CMakeLists.txt
  Likhashva/source/GreedyAlg/GreedyAlg.cpp
  Likhashva/source/GreedyAlg/GreedyAlg.h
Labels: Защита - :heavy_check_mark:, Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#26 Kreysmann_lab2
  Kreysmann/lab2/Input.txt
  Kreysmann/lab2/Makefile
  Kreysmann/lab2/Source/A-star/astar.cpp
  Kreysmann/lab2/Source/A-star/astar.hpp
  Kreysmann/lab2/Source/A-star/main.cpp
  Kreysmann/lab2/Source/Greedy/greedy.cpp
  Kreysmann/lab2/Source/Greedy/greedy.hpp
  Kreysmann/lab2/Source/Greedy/main.cpp
  Kreysmann/lab2/report.pdf
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#45 Kreysmann_lab3
  Kreysmann/lab3/Makefile
  Kreysmann/lab3/Source/ford_fulkerson.cpp
  Kreysmann/lab3/Source/ford_fulkerson.hpp
  Kreysmann/lab3/Source/main.cpp
  Kreysmann/lab3/report.pdf
Labels: Код - можно поправить, Можно защищать, Отчёт - можно поправить, Режим: 2, С++

#36 Sosedkov_lab3
  Sosedkov/lab3/Source/lab3.py
  Sosedkov/lab3/Source/lab3_1.py
  Sosedkov/lab3/Tests/find_path_tests
  Sosedkov/lab3/Tests/max_flow_tests
  Sosedkov/lab3/report.pdf
  Sosedkov/lab3/run_tests.py
Labels: Python, Защита - :fire:, Код - исправить, Отчёт - можно поправить, Режим: 3, Тесты - можно поправить

#40 Kamzolov_lab3
  Kamzolov/lab3/.gitignore
  Kamzolov/lab3/Makefile
  Kamzolov/lab3/Source/FordFulkerson.cpp
  Kamzolov/lab3/Source/FordFulkerson.h
  Kamzolov/lab3/Source/main.cpp
  Kamzolov/lab3/Tests/FordFulkersonTest.cpp
  Kamzolov/lab3/report.pdf
Labels: Код - можно поправить, Можно защищать, Отчёт - можно поправить, Режим: 3, С++

#42 Mosin_lab3
  Mosin/lab3/Headers/API.h
  Mosin/lab3/Makefile
  Mosin/lab3/Source/API.cpp
  Mosin/lab3/Source/main.cpp
  Mosin/lab3/Tests/test.cpp
  Mosin/lab3/report_Alg_lab3.pdf
Labels: Можно защищать, Режим: 3, С++

#41 Gladkikh_lab3
  Gladkikh/lab3/makefile
  Gladkikh/lab3/report.pdf
  Gladkikh/lab3/source/graph.cpp
  Gladkikh/lab3/source/graph.hpp
  Gladkikh/lab3/source/main.cpp
  Gladkikh/lab3/test/test.cpp
Labels: Код - :1st_place_medal:, Код - можно поправить, Можно защищать, Отчёт - можно поправить, Режим: 3, С++, Тесты - :1st_place_medal:

#44 Chebesova_lab3
  Chebesova/lab1/9383_Chebesova_lab1.pdf
  Chebesova/lab1/run.sh
  Chebesova/lab1/source/lab1.cpp
  Chebesova/lab3/9383_Chebesova_LR3.pdf
  Chebesova/lab3/sourse/main.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#46 Lapina_lab3
  Lapina/lb3/Lapina_Anastasia_LB3.pdf
  Lapina/lb3/Makefile
  Lapina/lb3/source/lb3.cpp
  Lapina/lb3/source/lb3.hpp
  Lapina/lb3/source/main.cpp
  Lapina/lb3/test/tests_programm.cpp
Labels: Код - можно поправить, Можно защищать, Можно не исправлять, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#47 Khotiakov_lab2
  Khotiakov/lab2/report.pdf
  Khotiakov/lab2/src/astar.cpp
  Khotiakov/lab2/src/grid.cpp
Labels: Жду исправления......., Код - :1st_place_medal:, Можно защищать, Отчёт - исправить, Режим: 2, С++

#31 Rybnikov_lab2
  Rybnikov/9383_Рыбников_lab2.pdf
  Rybnikov/Tests/Test.txt
  Rybnikov/src/AStar.cpp
  Rybnikov/src/AStar.h
  Rybnikov/src/GreedyAlg.cpp
  Rybnikov/src/GreedyAlg.h
  Rybnikov/src/Makefile
  Rybnikov/src/Option.cpp
  Rybnikov/src/Option.h
  Rybnikov/src/Orgraph.cpp
  Rybnikov/src/Orgraph.h
  Rybnikov/src/main.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#38 Rybnikov_lab3
  Rybnikov/lab3/9383_Рыбников_ПиАА_lab3.pdf
  Rybnikov/lab3/Tests/test.txt
  Rybnikov/lab3/src/FF.cpp
  Rybnikov/lab3/src/FF.h
  Rybnikov/lab3/src/Makefile
  Rybnikov/lab3/src/Orgraph.cpp
  Rybnikov/lab3/src/Orgraph.h
  Rybnikov/lab3/src/main.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Режим: 2, С++

#52 Arutyunyan_lab3
  Arutyunyan/lab1/compile_variant1.sh
  Arutyunyan/lab1/compile_variant2.sh
  Arutyunyan/lab1/exec_tests
  Arutyunyan/lab1/report.odt
  Arutyunyan/lab1/report.pdf
  Arutyunyan/lab1/run_tests.sh
  Arutyunyan/lab1/source/backtracking.hpp
  Arutyunyan/lab1/source/field.cpp
  Arutyunyan/lab1/source/field.h
  Arutyunyan/lab1/source/variant1.cpp
  Arutyunyan/lab1/source/variant2.cpp
  Arutyunyan/lab1/tests/tests.cpp
  Arutyunyan/lab2/.idea/.gitignore
  Arutyunyan/lab2/.idea/lab2.iml
  Arutyunyan/lab2/.idea/misc.xml
  Arutyunyan/lab2/.idea/modules.xml
  Arutyunyan/lab2/.idea/vcs.xml
  Arutyunyan/lab2/compile_program.sh
  Arutyunyan/lab2/exec_tests
  Arutyunyan/lab2/report.pdf
  Arutyunyan/lab2/run_tests.sh
  Arutyunyan/lab2/source/a.out
  Arutyunyan/lab2/source/astar.hpp
  Arutyunyan/lab2/source/graph.hpp
  Arutyunyan/lab2/source/greedy.hpp
  Arutyunyan/lab2/source/main.cpp
  Arutyunyan/lab2/source/search_algorithms.h
  Arutyunyan/lab2/tests/tests.cpp
  Arutyunyan/lab3/execute_everything.sh
  Arutyunyan/lab3/execute_tests.sh
  Arutyunyan/lab3/report.pdf
  Arutyunyan/lab3/source/ford_falkerson.hpp
  Arutyunyan/lab3/source/graph.hpp
  Arutyunyan/lab3/source/main.cpp
  Arutyunyan/lab3/source/task_ford_falkerson.hpp
  Arutyunyan/lab3/tests/tests.cpp
Labels: Защита - :fire:, Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#58 Chebesova_lab2
  Chebesova/lab2/9383_Chebesova_ID_LR2.pdf
  Chebesova/lab2/sourse/astar.cpp
  Chebesova/lab2/sourse/grid.cpp
  Chebesova/lab3/9383_Chebesova_LR3.pdf
  Chebesova/lab3/sourse/main.cpp
Labels: Код - можно поправить, Можно защищать, Режим: 1, С++

#32 Sergienkova_lab2
  Sergienkova/lab2/9383_Сергиенкова_lab2.pdf
  Sergienkova/lab2/9383_Сергиенкова_lb2.docx
  Sergienkova/lab2/Test.txt
  Sergienkova/lab2/src/Edge.cpp
  Sergienkova/lab2/src/Edge.h
  Sergienkova/lab2/src/Graph.cpp
  Sergienkova/lab2/src/Graph.h
  Sergienkova/lab2/src/Makefile
  Sergienkova/lab2/src/Resolver.cpp
  Sergienkova/lab2/src/Resolver.h
  Sergienkova/lab2/src/Resolver2.cpp
  Sergienkova/lab2/src/Resolver2.h
  Sergienkova/lab2/src/Resolver3.cpp
  Sergienkova/lab2/src/Resolver3.h
  Sergienkova/lab2/src/main.cpp
Labels: Можно защищать

#39 Sergienkova_lab3
  Sergienkova/lab3/9383_Сергиенкова_fix_lb3.pdf
  Sergienkova/lab3/Ex1.txt
  Sergienkova/lab3/src/Edge.cpp
  Sergienkova/lab3/src/Edge.h
  Sergienkova/lab3/src/Finder.cpp
  Sergienkova/lab3/src/Finder.h
  Sergienkova/lab3/src/Graph.cpp
  Sergienkova/lab3/src/Graph.h
  Sergienkova/lab3/src/Makefile
  Sergienkova/lab3/src/Resolver.cpp
  Sergienkova/lab3/src/Resolver.h
  Sergienkova/lab3/src/main.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#37 Likhashva_lab3
  Likhashva/lab3/CMakeLists.txt
  Likhashva/lab3/LB3_Lihashva_AD_9383.pdf
  Likhashva/lab3/source/lab3.cpp
  Likhashva/lab3/source/lab3.h
Labels: Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#19 Zvega_lab2
  zvega/lab2/a_star_simple.py
  zvega/lab2/a_star_task.py
  zvega/lab2/greed.py
  zvega/lab2/report.pdf
  zvega/lab2/test/Tests/tests_a_star.txt
  zvega/lab2/test/Tests/tests_matrix.txt
  zvega/lab2/test/a_star.py
  zvega/lab2/test/test.py
Labels: Python, Можно защищать, Режим: 3, Тесты - можно поправить

#62 Mosin_lab4
  Mosin/lab4/Headers/API.h
  Mosin/lab4/Makefile
  Mosin/lab4/Source/API.cpp
  Mosin/lab4/Source/lab4_1.cpp
  Mosin/lab4/Source/lab4_2.cpp
  Mosin/lab4/Tests/test.cpp
  Mosin/lab4/report.pdf
Labels: Можно защищать, С++

#43 Nistratov_lab3
  Nistratov/lab3/Makefile
  Nistratov/lab3/PiAA_lab3_reworked.pdf
  Nistratov/lab3/source/ford_falk.cpp
  Nistratov/lab3/source/ford_falk.h
  Nistratov/lab3/source/main.cpp
  Nistratov/lab3/tests/test.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#57 Nistratov_lab4
  Nistratov/lab4/Makefile
  Nistratov/lab4/PiAA_lab4_report.pdf
  Nistratov/lab4/source/lab4_1.cpp
  Nistratov/lab4/source/lab4_1.hpp
  Nistratov/lab4/source/lab4_2.cpp
  Nistratov/lab4/source/lab4_2.hpp
  Nistratov/lab4/source/main_1.cpp
  Nistratov/lab4/source/main_2.cpp
  Nistratov/lab4/tests/test_1.cpp
  Nistratov/lab4/tests/test_2.cpp
Labels: Можно защищать, С++

#54 Likhashva_lab4
  Likhashva/lab4/LB4_Lihashva_AD_9383.pdf
  Likhashva/lab4/source/lab4_1/CMakeLists.txt
  Likhashva/lab4/source/lab4_1/lab4_1.cpp
  Likhashva/lab4/source/lab4_1/lab4_1.h
  Likhashva/lab4/source/lab4_2/CMakeLists.txt
  Likhashva/lab4/source/lab4_2/lab4_2.cpp
  Likhashva/lab4/source/lab4_2/lab4_2.h
Labels: Можно защищать, С++

#22 Update field.cpp
  Moiseychenko/lab1/source/field.cpp
Labels: Взял на карандаш

#68 Moiseychenko_lab2
  Moiseychenko/lab2/Makefile
  Moiseychenko/lab2/report_lab2.pdf
  Moiseychenko/lab2/source/graph.cpp
  Moiseychenko/lab2/source/graph.h
  Moiseychenko/lab2/source/main.cpp
Labels: Защита - :heavy_check_mark:, Можно защищать, Режим: 2, С++

#50 Lapina_lab4
  Lapina/lb4/.~lock.Lapina_Anastasia_LB4.odt#
  Lapina/lb4/Lapina_Anastasia_LB4.pdf
  Lapina/lb4/task1/Makefile
  Lapina/lb4/task1/source/lb4_1.cpp
  Lapina/lb4/task1/source/lb4_1.hpp
  Lapina/lb4/task1/source/main.cpp
  Lapina/lb4/task1/test/tests_programm.cpp
  Lapina/lb4/task2/Makefile
  Lapina/lb4/task2/source/lb4_2.cpp
  Lapina/lb4/task2/source/lb4_2.hpp
  Lapina/lb4/task2/source/main.cpp
  Lapina/lb4/task2/test/tests_programm.cpp
Labels: Код - можно поправить, Можно защищать, С++

#55 Kamzolov_lab4
  Kamzolov/lab4/.gitignore
  Kamzolov/lab4/Makefile
  Kamzolov/lab4/Source/KMP/KMP.cpp
  Kamzolov/lab4/Source/KMP/KMP.h
  Kamzolov/lab4/Source/main_1.cpp
  Kamzolov/lab4/Source/main_2.cpp
  Kamzolov/lab4/Tests/KMPTest.cpp
  Kamzolov/lab4/report.pdf
Labels: Можно защищать, С++

#48 Kreysmann_lab4
  Kreysmann/lab4/Makefile
  Kreysmann/lab4/Source/task1/main.cpp
  Kreysmann/lab4/Source/task1/task1.cpp
  Kreysmann/lab4/Source/task1/task1.hpp
  Kreysmann/lab4/Source/task2/main.cpp
  Kreysmann/lab4/Source/task2/task2.cpp
  Kreysmann/lab4/Source/task2/task2.hpp
  Kreysmann/lab4/report.pdf
Labels: Можно защищать, С++

#70 Karpekina_lab4
  Karpekina/lab4/Karpekina_AA_lb4.odt
  Karpekina/lab4/Karpekina_AA_lb4.pdf
  Karpekina/lab4/Source/lb4_1.cpp
  Karpekina/lab4/Source/lb4_2.cpp
Labels: С++

#73 Zvega_lab3
  zvega/lab3/lab3.py
  zvega/lab3/lab3_6.py
  zvega/lab3/report.pdf
Labels: Python

#56 Gladkikh_lab4
  Gladkikh/lab4/makefile
  Gladkikh/lab4/report.pdf
  Gladkikh/lab4/source/kmp.cpp
  Gladkikh/lab4/source/kmp.hpp
  Gladkikh/lab4/source/main.cpp
  Gladkikh/lab4/test/test.cpp
Labels: Можно защищать, С++

#51 Khotiakov_lab3
  Khotiakov/lab3/report.pdf
  Khotiakov/lab3/source/main.cpp
Labels: Код - можно поправить, Можно защищать, Отчёт - можно поправить, Режим: 2, С++
