Repository makometr/piaa_9383, pull requests merged in 2021-03, with the labels that each got.

#1 Kamzolov_lab1
  Kamzolov/lab1/Makefile
  Kamzolov/lab1/Source/Table.cpp
  Kamzolov/lab1/Source/Table.hpp
  Kamzolov/lab1/Source/main.cpp
  Kamzolov/lab1/Tests/algosTest.cpp
  Kamzolov/lab1/report.pdf
Labels: Защита - :fire:, Можно защищать, Режим: 3, С++, Тесты - :1st_place_medal:

#3 Gladkikh_lab1
  Gladkikh/lab1/makefile
  Gladkikh/lab1/report.pdf
  Gladkikh/lab1/source/Field.cpp
  Gladkikh/lab1/source/Field.h
  Gladkikh/lab1/source/Square.h
  Gladkikh/lab1/source/main.cpp
  Gladkikh/lab1/test/test_field.cpp
Labels: Защита - :fire:, Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#4 Likhashva_lab1
  Likhashva/lab1/CMakeLists.txt
  Likhashva/lab1/LB1_Lihashva_AD_9383.pdf
  Likhashva/lab1/source/lab.cpp
  Likhashva/lab1/source/lab.h
Labels: Защита - :fire:, Код - можно поправить, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#7 Kreysmann lab1
  Kreysmann/lab1/Makefile
  Kreysmann/lab1/Source/backTracking.cpp
  Kreysmann/lab1/Source/header.hpp
  Kreysmann/lab1/Source/main.cpp
  Kreysmann/lab1/Tests/includeCatch.hpp
  Kreysmann/lab1/Tests/tests-main.cpp
  Kreysmann/lab1/Tests/tests.cpp
  Kreysmann/lab1/report.pdf
Labels: Защита - :fire:, Код - можно поправить, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#8 Sosedkov_lab1
  Sosedkov/lab1/Source/lab1_rect_field.py
  Sosedkov/lab1/Source/lab1_square_field.py
  Sosedkov/lab1/Tests/create_square_tests.txt
  Sosedkov/lab1/Tests/find_free_rect_tests.txt
  Sosedkov/lab1/Tests/tests.txt
  Sosedkov/lab1/report.pdf
  Sosedkov/lab1/run_tests.py
Labels: Python, Защита - :fire:, Режим: 3

#9 Mosin_lab1
  Mosin/lab1/Headers/API.h
  Mosin/lab1/Makefile
  Mosin/lab1/Source/API.cpp
  Mosin/lab1/Source/main.cpp
  Mosin/lab1/Tests/test.cpp
  Mosin/lab1/report_Alg_lab1.pdf
Labels: Защита - :fire:, Режим: 3, Тесты - :1st_place_medal:

#11 Khotiakov_lab1
  Khotiakov/lab1/MakeFile
  Khotiakov/lab1/report.pdf
  Khotiakov/lab1/source/Table.cpp
  Khotiakov/lab1/source/Table.h
  Khotiakov/lab1/source/main.cpp
Labels: Защита - :fire:, Код - :1st_place_medal:, Отчёт - :1st_place_medal:, Режим: 2, С++

#12 Nistratov_lab1
  Nistratov/lab1/Makefile
  Nistratov/lab1/PIAA_lab1_report.pdf
  Nistratov/lab1/source/main.cpp
  Nistratov/lab1/source/square.cpp
  Nistratov/lab1/source/square.h
  Nistratov/lab1/tests/test.cpp
Labels: Защита - :fire:, Отчёт - :1st_place_medal:, Режим: 3, С++

#14 Moiseychenko_lab1
  Moiseychenko/lab1/Makefile
  Moiseychenko/lab1/report.pdf
  Moiseychenko/lab1/source/field.cpp
  Moiseychenko/lab1/source/field.h
  Moiseychenko/lab1/source/main0.cpp
  Moiseychenko/lab1/source/main1.cpp
Labels: Защита - :fire:, Режим: 2, С++
