Repository makometr/piaa_9383, pull requests merged in 2021-06, with the labels that each got.

#74 Nozdrin_lab2
  Nozdrin/lab2/A.cpp
  Nozdrin/lab2/Achar.cpp
  Nozdrin/lab2/CMakeLists.txt
  Nozdrin/lab2/greedy.cpp
  Nozdrin/lab2/main.cpp
  Nozdrin/lab2/report.odt
  Nozdrin/lab2/report.pdf
Labels: Код - :1st_place_medal:, Можно защищать, Режим: 2, С++

#75 Rybnikov_lab4
  Rybnikov/lab4/9383_Рыбников_lb4.pdf
  Rybnikov/lab4/Tests/test1.txt
  Rybnikov/lab4/Tests/test2.txt
  Rybnikov/lab4/Tests/test3.txt
  Rybnikov/lab4/src/KMP.cpp
  Rybnikov/lab4/src/KMP.hpp
  Rybnikov/lab4/src/Makefile
  Rybnikov/lab4/src/main.cpp
Labels: Код - можно поправить, Можно защищать, С++

#76 Lapina_lab5
  Lapina/lb5/Lapina_Anastasia_lb5.pdf
  Lapina/lb5/task1/Makefile
  Lapina/lb5/task1/source/lb5_1.cpp
  Lapina/lb5/task1/source/lb5_1.hpp
  Lapina/lb5/task1/source/main.cpp
  Lapina/lb5/task2/Makefile
  Lapina/lb5/task2/source/lb5_2.cpp
  Lapina/lb5/task2/source/lb5_2.hpp
  Lapina/lb5/task2/source/main.cpp
Labels: Можно защищать, Режим: 1, С++

#60 Kreysmann_lab5
  Kreysmann/lab5/Makefile
  Kreysmann/lab5/Source/task1/main.cpp
  Kreysmann/lab5/Source/task1/task1.cpp
  Kreysmann/lab5/Source/task1/task1.hpp
  Kreysmann/lab5/Source/task2/main.cpp
  Kreysmann/lab5/Source/task2/task2.cpp
  Kreysmann/lab5/Source/task2/task2.hpp
  Kreysmann/lab5/report.pdf
Labels: Код - :1st_place_medal:, Можно защищать, Режим: 1, С++

#71 Orlov_lab2
  Orlov/lab2/Orlov_Daniil_LB2.pdf
  Orlov/lab2/compile_lab2.sh
  Orlov/lab2/src/main.cpp
Labels: Можно защищать, Отчёт - можно поправить, Режим: 2, С++

#81 Sosedkov lab4
  Sosedkov/lab4/Source/lab4_cycle.py
  Sosedkov/lab4/Source/lab4_kmp.py
  Sosedkov/lab4/Tests/kmp_tests.txt
  Sosedkov/lab4/Tests/prefix_tests.txt
  Sosedkov/lab4/report.pdf
  Sosedkov/lab4/run_tests.py
Labels: Python, Можно защищать

#83 Sergienkova lab4
  Sergienkova/lab4/9383_Сергиенкова_lb4.pdf
  Sergienkova/lab4/Tests/test1.txt
  Sergienkova/lab4/Tests/test2.txt
  Sergienkova/lab4/src/Makefile
  Sergienkova/lab4/src/main.cpp
Labels: С++

#78 Gladkikh lab5
  Gladkikh/lab5/makefile
  Gladkikh/lab5/report.pdf
  Gladkikh/lab5/source/task1/ahocorasick.cpp
  Gladkikh/lab5/source/task1/ahocorasick.hpp
  Gladkikh/lab5/source/task1/main.cpp
  Gladkikh/lab5/source/task2/ahocorasick.cpp
  Gladkikh/lab5/source/task2/ahocorasick.hpp
  Gladkikh/lab5/source/task2/main.cpp
Labels: Режим: 1, С++

#79 Kamzolov lab5
  Kamzolov/lab5/Makefile
  Kamzolov/lab5/Source/lab5_1/aho_corasick.cpp
  Kamzolov/lab5/Source/lab5_1/aho_corasick.h
  Kamzolov/lab5/Source/lab5_1/main.cpp
  Kamzolov/lab5/Source/lab5_2/aho_corasick.cpp
  Kamzolov/lab5/Source/lab5_2/aho_corasick.h
  Kamzolov/lab5/Source/lab5_2/main.cpp
  Kamzolov/lab5/report.pdf
Labels: Можно защищать, Можно не исправлять, Отчёт - :1st_place_medal:, Режим: 1, Режим: 3

#84 Nistratov lab5
  Nistratov/lab5/Makefile
  Nistratov/lab5/report_piaa5.pdf
  Nistratov/lab5/source/lab5_1.cpp
  Nistratov/lab5/source/lab5_1.hpp
  Nistratov/lab5/source/lab5_2.cpp
  Nistratov/lab5/source/lab5_2.hpp
  Nistratov/lab5/source/main_1.cpp
  Nistratov/lab5/source/main_2.cpp
  Nistratov/lab5/tests/test_1.cpp
  Nistratov/lab5/tests/test_2.cpp
Labels: Отчёт - :1st_place_medal:, Режим: 3, С++

#89 Orlov_lab3
  Orlov/lab3/Orlov_Daniil_lb3.docx
  Orlov/lab3/Orlov_Daniil_lb3.pdf
  Orlov/lab3/compile_lab3.sh
  Orlov/lab3/src/main.cpp
Labels: Режим: 2, С++

#82 Sosedkov lab5
  Sosedkov/lab5/Source/lab5.py
  Sosedkov/lab5/Source/lab5_1.py
  Sosedkov/lab5/Source/lab5_2.py
  Sosedkov/lab5/Tests/aho_tests.txt
  Sosedkov/lab5/Tests/cut_tests.txt
  Sosedkov/lab5/report.pdf
  Sosedkov/lab5/run_tests.py
Labels: Python, Режим: 2

#90 Poplavskiy lab5
  Poplavskiy/lab5/9383_Poplavskiy_lab5.pdf
  Poplavskiy/lab5/PiAA5_1/PiAA5_1/PiAA5_1.cpp
  Poplavskiy/lab5/PiAA5_1/PiAA5_1/data_tests_1.txt
  Poplavskiy/lab5/PiAA5_1/PiAA5_1/data_tests_2.txt
  Poplavskiy/lab5/PiAA5_1/PiAA5_1/data_tests_3.txt
  Poplavskiy/lab5/PiAA5_1/PiAA5_1/piaa5_1.hpp
  Poplavskiy/lab5/PiAA5_1/PiAA5_1/tests_1.cpp
  Poplavskiy/lab5/PiAA5_2/PiAA5_2/PiAA5_2.cpp
  Poplavskiy/lab5/PiAA5_2/PiAA5_2/data_tests_1.txt
  Poplavskiy/lab5/PiAA5_2/PiAA5_2/data_tests_2.txt
  Poplavskiy/lab5/PiAA5_2/PiAA5_2/data_tests_3.txt
  Poplavskiy/lab5/PiAA5_2/PiAA5_2/piaa5_2.hpp
  Poplavskiy/lab5/PiAA5_2/PiAA5_2/tests_2.cpp
Labels: Режим: 2

#98 Orlov_lab5
  Orlov/lab5/Orlov_lab5.docx
  Orlov/lab5/Orlov_lab5.pdf
  Orlov/lab5/compile_lab5.sh
  Orlov/lab5/compile_lab5_joker.sh
  Orlov/lab5/src/lab5.cpp
  Orlov/lab5/src/lab5_joker.cpp
Labels: С++
