Repository makometr/piaa_9383, pull requests merged in 2021-04, with the labels that each got.

#6 Arutyunyan_lab1
  Arutyunyan/lab1/compile_variant1.sh
  Arutyunyan/lab1/compile_variant2.sh
  Arutyunyan/lab1/report.pdf
  Arutyunyan/lab1/run_tests.sh
  Arutyunyan/lab1/source/backtracking.hpp
  Arutyunyan/lab1/source/field.cpp
  Arutyunyan/lab1/source/field.h
  Arutyunyan/lab1/source/variant1.cpp
  Arutyunyan/lab1/source/variant2.cpp
  Arutyunyan/lab1/tests/tests.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#15 Poplavskiy_lab1
  Poplavskiy/lab1/Poplavskiy_lab1.pdf
  Poplavskiy/lab1/src/Square.h
  Poplavskiy/lab1/src/source.cpp
  Poplavskiy/lab1/src/tests.cpp
Labels: Код - можно поправить, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - можно поправить

#2 Lapina_Anastasia_lab1
  Lapina/lab1/Lapina_Anastasia_LB1.pdf
  Lapina/lab1/Makefile
  Lapina/lab1/source/lb1.cpp
  Lapina/lab1/source/lb1.hpp
  Lapina/lab1/source/main.cpp
  Lapina/lab1/test/tests_programm.cpp
Labels: Можно защищать, Можно не исправлять, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#28 Lapina_lb2
  Lapina/lb2/Lapina_Anastasia_LB2.pdf
  Lapina/lb2/Makefile
  Lapina/lb2/source/lb2.cpp
  Lapina/lb2/source/lb2.hpp
  Lapina/lb2/source/main.cpp
  Lapina/lb2/test/tests_programm.cpp
Labels: Код - можно поправить, Можно защищать, Отчёт - исправить, Режим: 3, С++, Тесты - можно поправить

#5 Rybnikov lab1
  Rybnikov/9383_Рыбников_ lb1.pdf
  Rybnikov/Makefile
  Rybnikov/Test.txt
  Rybnikov/main.cpp
Labels: Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#10 Sergienkova lab1
  Sergienkova/9383_Сергиенкова_ lb1.pdf
  Sergienkova/src/Makefile
  Sergienkova/src/Position.cpp
  Sergienkova/src/Position.h
  Sergienkova/src/Resolver.cpp
  Sergienkova/src/Resolver.h
  Sergienkova/src/Tile.cpp
  Sergienkova/src/Tile.h
  Sergienkova/src/main.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++

#13 Chebesova_lab1
  Chebesova/lab1/9383_Chebesova_lab1.pdf
  Chebesova/lab1/run.sh
  Chebesova/lab1/source/lab1.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - :1st_place_medal:, Режим: 2, С++

#17 Zvega_lab1
  zvega/lab1/Source/rect_lab1.py
  zvega/lab1/Source/square.py
  zvega/lab1/Tests/tests.txt
  zvega/lab1/Tests/tests_check_box.txt
  zvega/lab1/Tests/tests_paving.txt
  zvega/lab1/report.pdf
  zvega/lab1/test.py
Labels: Python, Код - исправить, Отчёт - исправить, Режим: 3, Тесты - исправить

#20 Gladkikh_lab2
  Gladkikh/lab2/makefile
  Gladkikh/lab2/report.pdf
  Gladkikh/lab2/source/graph.cpp
  Gladkikh/lab2/source/graph.hpp
  Gladkikh/lab2/source/main.cpp
  Gladkikh/lab2/test/test.cpp
Labels: Код - можно поправить, Можно защищать, Отчёт - можно поправить, Режим: 3, С++, Тесты - :1st_place_medal:

#21 Kamzolov_lab2
  Kamzolov/lab2/.gitignore
  Kamzolov/lab2/Makefile
  Kamzolov/lab2/Source/A_star/a_star.cpp
  Kamzolov/lab2/Source/A_star/a_star.h
  Kamzolov/lab2/Source/A_star/main.cpp
  Kamzolov/lab2/Source/Greedy/greedy.cpp
  Kamzolov/lab2/Source/Greedy/greedy.h
  Kamzolov/lab2/Source/Greedy/main.cpp
  Kamzolov/lab2/Test/a_starTest.cpp
  Kamzolov/lab2/Test/greedyTest.cpp
  Kamzolov/lab2/report.pdf
Labels: Можно защищать, Отчёт - :1st_place_medal:, Режим: 3, С++, Тесты - :1st_place_medal:

#25 Nistratov_lab2
  Nistratov/lab2/Makefile
  Nistratov/lab2/PIAA_lab2_report.pdf
  Nistratov/lab2/source/graph.cpp
  Nistratov/lab2/source/graph.h
  Nistratov/lab2/source/greedy.cpp
  Nistratov/lab2/source/greedy.h
  Nistratov/lab2/source/mainA.cpp
  Nistratov/lab2/source/mainG.cpp
  Nistratov/lab2/tests/testA.cpp
  Nistratov/lab2/tests/testG.cpp
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - можно поправить, Режим: 3, С++, Тесты - :1st_place_medal:

#27 Mosin_lab2
  Mosin/lab2/Headers/API.h
  Mosin/lab2/Makefile
  Mosin/lab2/Source/API.cpp
  Mosin/lab2/Source/main.cpp
  Mosin/lab2/Tests/test.cpp
  Mosin/lab2/report_Alg_lab2.pdf
Labels: Код - :1st_place_medal:, Можно защищать, Отчёт - исправить, Режим: 3, С++, Тесты - :1st_place_medal:

#29 Sosedkov_lab2
  Sosedkov/lab2/Source/lab2_astar.py
  Sosedkov/lab2/Source/lab2_greedy.py
  Sosedkov/lab2/Tests/a_star_tests.txt
  Sosedkov/lab2/Tests/greedy_tests.txt
  Sosedkov/lab2/Tests/heuristic_tests.txt
  Sosedkov/lab2/report.pdf
  Sosedkov/lab2/run_tests.py
Labels: Python, Можно защищать, Отчёт - исправить, Режим: 3, Тесты - можно поправить

#30 Arutyunyan_lab2
  Arutyunyan/lab1/exec_tests
  Arutyunyan/lab1/report.odt
  Arutyunyan/lab2/.idea/.gitignore
  Arutyunyan/lab2/.idea/lab2.iml
  Arutyunyan/lab2/.idea/misc.xml
  Arutyunyan/lab2/.idea/modules.xml
  Arutyunyan/lab2/.idea/vcs.xml
  Arutyunyan/lab2/compile_program.sh
  Arutyunyan/lab2/exec_tests
  Arutyunyan/lab2/report.pdf
  Arutyunyan/lab2/run_tests.sh
  Arutyunyan/lab2/source/a.out
  Arutyunyan/lab2/source/astar.hpp
  Arutyunyan/lab2/source/graph.hpp
  Arutyunyan/lab2/source/greedy.hpp
  Arutyunyan/lab2/source/main.cpp
  Arutyunyan/lab2/source/search_algorithms.h
  Arutyunyan/lab2/tests/tests.cpp
Labels: Можно защищать
